### ISSUE TITLE
Placeholder %order% should be replaced with order number, not ID

### ISSUE THREAD

**Issue by iggypomp** [marlevak/Croatian-payment-slip-generator-for-WooCommerce#4]
If one is using custom order numbers, they will have no clue where to look for specific order, so they need order number, not ID. If this number is the same, there will be no changes.

I changed it already, but it could be implemented to this plugin.

In wooplatnica.php

 $order->get_id(),

could be replaced with

$order->get_order_number(),

I'm new here so I don't really know what I am doing.

Hope I've been helpful.

**Comment by marlevak** [comment]
Woow, I didn't know that _WC_Order_ class contains such a method nor that there exist plugin for that.

From security/privacy aspect, it makes sense not to expose the value of order id attribute to the user, since those identifiers are sequentially incremented and user could track how are sales of some web-shop going. At example, if user creates order on web-shop in time point T1 and finds out that the order id is 1030, and in time point T2 creates another one and finds out that now the order id is 1050, then it could be concluded that 20 orders were made in the period between T1 and T2.

Since your suggestion is valid and welcome, as well as your proposed code changes produce expected behavior, you can formally submit changes.
The easiest way would be to propose file change (especially since your changes are affecting only one file). To do so, in the home page of the repository you click on the file you want to edit, then press edit button (it is represented with Pencil icon in the upper-right corner) and then replace all occurrences of "$order->get_id()" with "$order->get_order_number()".
Finally you should at the end of that page specify in the first text-field the title of that file-change proposal (a.k.a. the name of the pull request), which could be something like "Replace calls of get_id method with get_order_number of WC_Order class". Last thing to do is to specify some description and for that you can copy-paste the first paragraph of your post in this issue. After that you submit your pull request by pressing "Propose file change" button and then you have to wait until I review your code and merge it.

If you stuck on any step, feel free to ask.

**Comment by iggypomp** [comment]
Thank you for detailed instructions. Think I got it.
